"""add pembelian table

Revision ID: 3d2f9a04fdb3
Revises: 938ef06e4580
Create Date: 2025-04-19 03:14:36.409376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2f9a04fdb3'
down_revision = '938ef06e4580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembelian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('bukti_pembayaran', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembelian')
    # ### end Alembic commands ###
