"""Initial clean migration

Revision ID: 938ef06e4580
Revises: 
Create Date: 2025-04-18 23:52:32.496969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938ef06e4580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('satuan', sa.String(length=20), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('tanggal_kadaluarsa', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forecast_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obat_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('hasil', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['obat_id'], ['obat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penggunaan_obat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obat_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obat_id'], ['obat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permintaan_obat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_peminta', sa.String(length=100), nullable=False),
    sa.Column('obat_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['obat_id'], ['obat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('resep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dokter_id', sa.Integer(), nullable=False),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dokter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pasien_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resep_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('penggunaan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penggunaan_id'], ['penggunaan_obat.id'], ),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resep_item')
    op.drop_table('resep')
    op.drop_table('user')
    op.drop_table('permintaan_obat')
    op.drop_table('penggunaan_obat')
    op.drop_table('forecast_result')
    op.drop_table('role')
    op.drop_table('obat')
    # ### end Alembic commands ###
