"""add jumlah to resep_item

Revision ID: e034cc8d3a23
Revises: 3d2f9a04fdb3
Create Date: 2025-04-19 05:07:55.507587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e034cc8d3a23'
down_revision = '3d2f9a04fdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pembelian', schema=None) as batch_op:
        batch_op.alter_column('pasien_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('resep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bukti_pembayaran',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('resep_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resep_item', schema=None) as batch_op:
        batch_op.drop_column('jumlah')

    with op.batch_alter_table('pembelian', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('bukti_pembayaran',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('resep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pasien_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
